### ISSUE TITLE
Input parsing failures shouldn't show up in stdout

### ISSUE THREAD

**Issue by JoshKarpel** [JoshKarpel/counterweight#78]
Seems like if there's an error in `read_keys()` it ends up making its way to stdout - probably need to catch exceptions here to make sure the app doesn't break in that case

Particularly here https://github.com/JoshKarpel/counterweight/blob/c7506120bfc224c4a42b799294dad25f3dc393cc/counterweight/input.py#L36 which is not currently inside the try-catch below it

**Comment by terencezl** [comment]
`b` is It's a variation of 
<img width="115" alt="image" src="https://github.com/JoshKarpel/counterweight/assets/3190888/e3f9d513-2dda-4cf5-8ecd-ecef51dfadb9"> on MacOS.

The last byte is different every time, despite the same mouse movement direction.

**Comment by JoshKarpel** [comment]
Those last bytes should represent the mouse coordinates, so it's possible that it's not valid UTF-8, which is probably the source of the problem. Probably need to play with the parser more. Surprised I haven't seen the same testing on Linux 🤔

**Comment by JoshKarpel** [comment]
@terencezl could you check out #83 on your system and see if that solves your problem? You shouldn't see any errors in `counterweight check-input --mouse` https://github.com/JoshKarpel/counterweight/blob/e2cc45da0cfdfac907dfd0bdf947b685dddfd905/counterweight/cli.py#L43-L47, and also hopefully meaningful mouse movement events (that I am not 100% sure on, mouse events are complicated).

**Comment by edrogers** [comment]
I was able to reproduce this issue on my machine. (python 3.11.7 on Xubuntu running X11.) After some poking around, I see that (as of 0.0.3) the mouse movements are being tracked and decoded as UTF-8. The bytes include the (x, y) coordinates of the mouse cursor with respect to the upper corner of the terminal window, offset by 33. As a result, if x or y exceed 94 in the terminal, the coordinates read as bytes will be greater than 127. UTF-8 decoding fails noisily, as we've seen.

I gave #83 a test run, and it's a step forward, but not a complete fix. With that change, the cursor coordinates can exceed 94 and not cause decoding issues. However, whenever the x or y coordinate gets above 223*, the application crashes. (Quietly, though.) That's more pleasant than the noisy failures, but obviously still not ideal. 

This crash for very large terminals is, I think, due to a limitation in the VT encoding scheme. I suppose this is a slightly different issue, but with more-or-less the same cause: moving your mouse too far across a very large terminal.

I'm totally unfamiliar with `parsy`, but I suspect you might need to rewrite your parsers to handle vt_inputs for the case when you have extended coordinates. (Not sure what the extended encoding scheme is for my terminal.) I see that [Textual has written a fairly sophisticated XTermParser](https://github.com/Textualize/textual/blob/244e42c6fcfd4989de08c57ffc10db1e5fc87add/src/textual/_xterm_parser.py#L25) that actually loops through the sequence, matching against regexes along the way, to catch the various edge-cases during parsing. (I don't honestly follow it.)

At this point, I'm thoroughly out of my depth. But thought I'd provide feedback about a limitation I see on #83.

*Note: A curious behavior I've seen. The application doesn't crash when parsing coordinates in the range [223, 224, 225] (inclusive). Instead, it just assumes the coordinate is one of [-33, -32, -31] respectively. Only once the coordinate reaches 226 does a full application crash occur. I wasn't able to inspect the bytes carefully enough to understand this.

**Comment by JoshKarpel** [comment]
@edrogers I think your analysis is spot-on

While working on #83 I realized that my terminal (WSL Ubuntu 22.04) seemed to be hitting https://github.com/microsoft/terminal/issues/13165 , which meant that I was seeing the non-sgr style responses (see mouse tracking section starting on page ~45 of https://invisible-island.net/xterm/ctlseqs/ctlseqs.pdf). But I just realized that the sgr command *modifies* the tracking command, so I need to send both. I think I've got a local dev environment where I can see the other format now, so I should be able to adapt #83 to handle coordinates past 94.

re: very large terminals, I will play with that too. Definitely shouldn't crash in that case!

**Comment by JoshKarpel** [comment]
@edrogers could you try latest on #83 again? I think it should now work for any terminal size, including past ~226

**Comment by edrogers** [comment]
Tried #83 again on my system. I've got good news and bad news.

Good news, the application doesn't crash, regardless of mouse position. I also have reason to suspect it's correctly locating the coordinates of the cursor, even for large values of x and y.

Bad news, it looks like the mouse movements are consistently failing to parse. :confused: 

```text
counterweight check-input --mouse
Waiting for input...
2023-12-31 14:42:41 [error    ] Failed to parse input          bytes=b'\x1b[<35;245;69M' elapsed_ns=670_592 error=Exception('unreachable')
2023-12-31 14:42:41 [error    ] Failed to parse input          bytes=b'\x1b[<35;243;68M' elapsed_ns=462_246 error=Exception('unreachable')
2023-12-31 14:42:41 [error    ] Failed to parse input          bytes=b'\x1b[<35;242;67M' elapsed_ns=426_991 error=Exception('unreachable')
2023-12-31 14:42:41 [error    ] Failed to parse input          bytes=b'\x1b[<35;240;67M' elapsed_ns=417_586 error=Exception('unreachable')
```

The unreachable exception appears to be here, at the bottom of this match statement: https://github.com/JoshKarpel/counterweight/blob/fbe5a93fa5b51eb456c6c56b81433d2d92a89cf4/counterweight/keys.py#L296-L315

As an experiment, I tried again to move my mouse while checking input. This time while holding the mouse button down. When doing that, the input parses with plausible values:

```text
counterweight check-input --mouse
Waiting for input...
2023-12-31 14:54:26 [debug    ] Parsed user input              bytes=b'\x1b[<0;249;63M' elapsed_ns=876_114 inputs=[MouseDown(position=Position(x=248, y=62), button=1)]
Event: MouseDown(position=Position(x=248, y=62), button=1)
Waiting for input...
2023-12-31 14:54:26 [debug    ] Parsed user input              bytes=b'\x1b[<32;250;63M' elapsed_ns=728_625 inputs=[MouseDown(position=Position(x=249, y=62), button=1)]
Event: MouseDown(position=Position(x=249, y=62), button=1)
Waiting for input...
2023-12-31 14:54:26 [debug    ] Parsed user input              bytes=b'\x1b[<32;272;64M' elapsed_ns=609_715 inputs=[MouseDown(position=Position(x=271, y=63), button=1)]
Event: MouseDown(position=Position(x=271, y=63), button=1)
Waiting for input...
2023-12-31 14:54:26 [debug    ] Parsed user input              bytes=b'\x1b[<32;273;63M' elapsed_ns=142_428 inputs=[MouseDown(position=Position(x=272, y=62), button=1)]
Event: MouseDown(position=Position(x=272, y=62), button=1)
```

Could it be that my system has reversed `m` for `M` or something similarly confusing?

An additional clue: when I try to play wordle on this branch, the application no longer responds to my mouse, even if I move the mouse with the button down. So, buttons do no light up with color or respond to clicks.

**Comment by JoshKarpel** [comment]
> Could it be that my system has reversed m for M or something similarly confusing?

That does seem to be the case, though I can't understand why, at least based on the docs I linked above...

I reworked #83 so that it should account for that, please give it another try when you get a chance!

**Comment by edrogers** [comment]
It works great! Absolutely no problems, even for very large terminals.

Kudos!

**Comment by terencezl** [comment]
Very cool! They work for me and mouse activates various reactions.

**Comment by JoshKarpel** [comment]
Thanks all! Will merge #83 and do a release soon.
